### PR TITLE
fix: preserve children keys + respect disableKeyGeneration in children key generation

### LINKED ISSUE #191: Keys of children being overwritten
In the following line of code, the `key` of each child gets overwritten. This can cause destructive behaviour with certain components that rely on the user knowing and controlling the `key`.

For example, some open source components allow you to set a `key` on an item which is later referenced in a callback so you know which item was selected.

https://github.com/TroyAlford/react-jsx-parser/blob/e854bdd0f6b803c3cc208df7c8636e9f1d819017/source/components/JsxParser.tsx#L265

It also seems that enabling the `disableKeyGeneration` option doesn’t effect this block of code.

Perhaps it could be enhanced to check if a key is already present first and only update if not? Additionally I think it should also respect the option mentioned above for consistency with other areas of the code.

### PR DESCRIPTION
**Pull request by jonw09**
* If a `key` already exists on a given child component, use it rather than overwriting it.
* Only generate `key`s for `children` if `disableKeyGeneration` prop is `false`.

Fixes #191

### CODE REVIEW

File: source/components/JsxParser.tsx [hunk 1]
```diff
@@ -260,9 +260,10 @@ export default class JsxParser extends React.Component<TProps> {
 				children = undefined
 			} else if (children.length === 1) {
 				[children] = children
-			} else if (children.length > 1) {
-				// Add `key` to any child that is a react element (by checking if it has `.type`)
-				children = children.map((child, key) => ((child && child.type) ? { ...child, key } : child))
+			} else if (children.length > 1 && !this.props.disableKeyGeneration) {
+				// Add `key` to any child that is a react element (by checking if it has `.type`) if one
+				// does not already exist.
+				children = children.map((child, key) => ((child && child.type) ? { ...child, key: child.key || key } : child))
```
Comment (TroyAlford) [inline source/components/JsxParser.tsx:266]: This makes sense, though I think it might be a little cleaner as:
```ts
children = children.map((child, key) => (child?.type && !child?.key) ? { ...child, key } : child)
```

This prevents the minor foible of re-spreading the child in the event where it _does_ have a `key` already. What do you think?

Comment (TroyAlford) [reply source/components/JsxParser.tsx:266]: If you don't mind making the minor change, I'll get this released shortly. Sorry for the long delay.

**Comment by TroyAlford** [comment]
Released as `1.28.4` just now
